CREATE TABLE team (
    --id         INT         AUTO_INCREMENT,
    id         INTEGER     GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
    name       VARCHAR(40) NOT NULL,
    conference VARCHAR(3)  NOT NULL,
    division   VARCHAR(5)  NOT NULL,
    PRIMARY KEY(id)
);