INSERT INTO team (name, conference, division) VALUES
('New England Patriots', 'AFC', 'East'),
('Miami Dolphins', 'AFC', 'East'),
('Buffalo Bills', 'AFC', 'East'),
('New York Jets', 'AFC', 'East'),
('Pittsburg Steelers', 'AFC', 'North'),
('Baltimore Ravens', 'AFC', 'North'),
('Cincinnati Bengals', 'AFC', 'North'),
('Cleveland Browns', 'AFC', 'North'),
('Houston Texans', 'AFC', 'South'),
('Tennessee Titans', 'AFC', 'South'),
('Indianapolis Colts', 'AFC', 'South'),
('Jacksonville Jaguars', 'AFC', 'South'),
('Oakland Raiders', 'AFC', 'West'),
('Kansas City Chiefs', 'AFC', 'West'),
('Denver Broncos', 'AFC', 'West'),
('San Diego Chargers', 'AFC', 'West'),
('Dallas Cowboys', 'NFC', 'East'),
('New York Giants', 'NFC', 'East'),
('Washington Redskins', 'NFC', 'East'),
('Philadelphia Eagles', 'NFC', 'East'),
('Detroit Lions', 'NFC', 'North'),
('Green Bay Packers', 'NFC', 'North'),
('Minnesota Vikings', 'NFC', 'North'),
('Chicago Bears', 'NFC', 'North'),
('Atlanta Falcons', 'NFC', 'South'),
('Tampa Bay Buccaneers', 'NFC', 'South'),
('New Orleans Saints', 'NFC', 'South'),
('Carolina Panthers', 'NFC', 'South'),
('Seattle Seahawks', 'NFC', 'West'),
('Arizona Cardinals', 'NFC', 'West'),
('Los Angeles Rams', 'NFC', 'West'),
('San Francisco 49ers', 'NFC', 'West');
